import { Path } from "@effect/platform";
import { describe, expect, it } from "@effect/vitest";
import { Effect } from "effect";

import { prepareCardPreviewForUi, renderCardPreviewMarkdown } from "../src/card-preview";

describe("prepareCardPreviewForUi", () => {
  it.effect("prepares the question and answer with Raycast-compatible math", () =>
    Effect.gen(function* () {
      const result = yield* prepareCardPreviewForUi({
        workspacePath: "/decks",
        cardType: "qa",
        deckPath: "/decks/physics.md",
        question: "How are $E$, $m$, and $c$ related?",
        answer: "$E = mc^2$.",
        content: "",
      });

      expect(result).toEqual({
        _tag: "PreviewReady",
        cards: [
          {
            prompt: "How are \\(E\\), \\(m\\), and \\(c\\) related?",
            reveal: "\\(E = mc^2\\).",
          },
        ],
      });
    }).pipe(Effect.provide(Path.layer)),
  );

  it.effect("prepares every card generated by a cloze note", () =>
    Effect.gen(function* () {
      const result = yield* prepareCardPreviewForUi({
        workspacePath: "/decks",
        cardType: "cloze",
        deckPath: "/decks/geography.md",
        question: "",
        answer: "",
        content: "France: {{c1::Paris}}. Germany: {{c2::Berlin}}.",
      });

      expect(result).toEqual({
        _tag: "PreviewReady",
        cards: [
          {
            prompt: "France: **[...]**. Germany: Berlin.",
            reveal: "France: **Paris**. Germany: Berlin.",
          },
          {
            prompt: "France: Paris. Germany: **[...]**.",
            reveal: "France: Paris. Germany: **Berlin**.",
          },
        ],
      });
    }).pipe(Effect.provide(Path.layer)),
  );

  it("shows the rendered question and answer together", () => {
    expect(
      renderCardPreviewMarkdown({
        prompt: "What is an effect?",
        reveal: "A description of a computation.",
      }),
    ).toBe("What is an effect?\n\n---\n\nA description of a computation.");
  });
});
